### ISSUE TITLE
[1.18/1.19] Inventorio Support

### ISSUE THREAD

**Issue by ConqAra** [jptrzy/trinkets-curios-theme-mod#3]
This might actually be the way to have people see the inventorio inventory with trinkets by adding support for this mod! If support was made, this could fix the trinkets api issue with inventorio by having this mod instead! [I've also posted this issue with the inventorio mod dev
](https://github.com/Lizard-Of-Oz/Inventorio/issues/129l)
![image](https://user-images.githubusercontent.com/76233356/178090069-70d93be2-81e4-4716-996c-8cc1a2e107dd.png)

![image](https://user-images.githubusercontent.com/76233356/178090056-43070211-f337-44c3-bfcf-34610f1b53ea.png)

**Comment by jptrzy** [comment]
I will look into it.

**Comment by jptrzy** [comment]
For now, I can't do anything, because of this [error](https://github.com/Lizard-Of-Oz/Inventorio/issues/135), but after it is fixed I will work on it.

**Comment by jptrzy** [comment]
For now, it looks like I shouldn't do anything on my end.

In depth, **Trinkets** mod is applying most important things in `PlayerScreenHandler`, which Inventorio mod isn't inhering in `InventorioScreen`, but creating its own  `InventorioScreenHandler` which isn't on its own based on `PlayerScreenHandler`.

*Never, should I describe code with my own words.*

Simple speaking, if I in my mod implement this (trinkets support for inventorio), it would be much bigger mess, then it is now.
