### ISSUE TITLE
The entrypoint "rei" is deprecated and must be changed to ensure future compatibility

### ISSUE THREAD

**Issue by SplendidAlakey** [jptrzy/trinkets-curios-theme-mod#6]
**MC** 1.19.2
**TrinketsCuriosTheme** 0.2.0
**REI** 9.1.528

![2022-08-16_21 07 51](https://user-images.githubusercontent.com/86702831/184962166-7db8cadf-dfea-4752-9042-9e41aa6b884b.png)

**Comment by jptrzy** [comment]
Thank you for reporting this. I will look into it.

**Comment by jptrzy** [comment]
Fixed in 0.2.2
